package by.epamtc.payment.controller.command;

public enum CommandName {
    LOGIN,
    REGISTRATION,
    TO_MAIN_PAGE,
    TO_LOGIN_PAGE,
    TO_REGISTRATION_PAGE,
    LOGOUT,
    CHANGE_LANGUAGE,
    TO_SETTING_PAGE,
    TO_USER_PAGE,
    TO_CARDS_PAGE,
    TO_CARD_SETTING_PAGE,
    TO_CARD_INFO_PAGE,
    TO_CARD_TRANSFER_PAGE,
    TO_ACCOUNTS_PAGE,
    CHANGE_CARD_STATUS,
    TRANSFER
}
